### ISSUE TITLE
bad ioctl syscall when building

### ISSUE THREAD

**Issue by nakedsushi** [Rillke/flac.js#7]
I'm building from source and it seems to build okay, but whenever I run the resulting JS files to encode a .wav file, I get this error:

```
abort("bad ioctl syscall 21523") at Error
    at jsStackTrace (eval at global.callEval (http://localhost:3000/flac/FlacEncoder.js:414:10), <anonymous>:1:18185)
    at stackTrace (eval at global.callEval (http://localhost:3000/flac/FlacEncoder.js:414:10), <anonymous>:1:18368)
    at abort (eval at global.callEval (http://localhost:3000/flac/FlacEncoder.js:414:10), <anonymous>:15:10936)
    at ___syscall54 (eval at global.callEval (http://localhost:3000/flac/FlacEncoder.js:414:10), <anonymous>:1:103969)
    at Rj (eval at global.callEval (http://localhost:3000/flac/FlacEncoder.js:414:10), <anonymous>:5:146550)
    at fh (eval at global.callEval (http://localhost:3000/flac/FlacEncoder.js:414:10), <anonymous>:5:9403)
    at th (eval at global.callEval (http://localhost:3000/flac/FlacEncoder.js:414:10), <anonymous>:5:29987)
    at Array.sh (eval at global.callEval (http://localhost:3000/flac/FlacEncoder.js:414:10), <anonymous>:5:29642)
    at Array.uf (eval at global.callEval (http://localhost:3000/flac/FlacEncoder.js:414:10), <anonymous>:6:66997)
    at lf (eval at global.callEval (http://localhost:3000/flac/FlacEncoder.js:414:10), <anonymous>:6:52858)
```

**Comment by Rillke** [comment]
@nakedsushi Removing the call to [ioctl](https://en.wikipedia.org/wiki/Ioctl) in [./flac/src/flac/utils.c](https://github.com/Rillke/flac/blob/775eb934f77e72e91528d857b293b4ec8c9e5be5/src/flac/utils.c#L188) did the job for me. [Emscripten doesn't support this one.](https://github.com/kripken/emscripten/issues/4451#issuecomment-235660073)

Do you have an idea where to undefine GWINSZ_IN_SYS_IOCTL in order to have a working build without too many code modifications?

**Comment by Rillke** [comment]
And, out of interest, how did you get the stack trace?

**Comment by nakedsushi** [comment]
I got the stacktrace from the message the worker was emitting `e.data.values`

**Comment by nakedsushi** [comment]
@Rillke I'm not sure what changes I'll have to make in ./flac/src/flac/utils.c to remove calls to ioctl.  Is it just in the includes section of that file?  I tried to just remove that line but couldn't get a working build at all.

On a related note, I posted the previous issue about Chrome crashing when trying to encode a larger flac file.  What I'm trying to do is build it w/ some tweaks (suggested here: https://github.com/kripken/emscripten/wiki/Chrome-Memory-Issues) and see if that helps w/ the memory usage.  Do you think any of those suggestions (--separate-asm, changing TOTAL_MEMORY) will help?

**Comment by pawohl** [comment]
> I got the stacktrace from the message the worker was emitting

Thanks!

> I'm not sure what changes I'll have to make in ./flac/src/flac/utils.c to remove calls to ioctl.

In [line 188](https://github.com/Rillke/flac/blob/775eb934f77e72e91528d857b293b4ec8c9e5be5/src/flac/utils.c#L188), there is a call to `ioctl` which causes the crash. Remove line 187 and 189 as well as they are pointless without line 188.
